// Renders every app icon, favicon and in-app logo from brand/logo.mjs.
//   node brand/build.mjs        (from the repo root; needs playwright's Chromium and python3 + Pillow)
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";
import * as logo from "./logo.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const mobile = join(root, "apps/mobile");
const jobs = []; // [svg, px, outPath, opaque]
const add = (svg, px, out, opaque = false) => jobs.push([svg, px, join(root, out), opaque]);

// --- web (site/ is served by the Worker)
writeFileSync(join(root, "site/favicon.svg"), logo.tile());
writeFileSync(join(root, "site/img/logo.svg"), logo.tile());
add(logo.square(), 180, "site/apple-touch-icon.png", true);
add(logo.tile(), 32, "site/favicon.png");
add(logo.tile(), 32, "site/favicon-32.png");
add(logo.tile(), 16, "site/favicon-16.png");
for (const px of [16, 32, 48]) add(logo.tile(), px, `brand/out/favicon-${px}.png`);
add(logo.tile(), 512, "site/img/logo-512.png");

// --- iOS (full bleed, no alpha; iOS rounds the corners)
const ios = "apps/mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset";
for (const [pt, scales] of [[20, [1, 2, 3]], [29, [1, 2, 3]], [40, [1, 2, 3]], [60, [2, 3]], [76, [1, 2]], [83.5, [2]], [1024, [1]]]) {
  for (const s of scales) add(logo.square(), Math.round(pt * s), `${ios}/Icon-App-${pt}x${pt}@${s}x.png`, true);
}

// --- macOS (draws its own rounded body + shadow)
for (const px of [16, 32, 64, 128, 256, 512, 1024]) add(logo.mac(), px, `apps/mobile/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_${px}.png`);

// --- Android: adaptive layers (108dp) + legacy round-square (48dp)
const res = "apps/mobile/android/app/src/main/res";
for (const [d, k] of [["mdpi", 1], ["hdpi", 1.5], ["xhdpi", 2], ["xxhdpi", 3], ["xxxhdpi", 4]]) {
  add(logo.tile(), 48 * k, `${res}/mipmap-${d}/ic_launcher.png`);
  add(logo.androidBackground(), 108 * k, `${res}/mipmap-${d}/ic_launcher_background.png`);
  add(logo.androidForeground(), 108 * k, `${res}/mipmap-${d}/ic_launcher_foreground.png`);
  add(logo.androidMonochrome(), 108 * k, `${res}/mipmap-${d}/ic_launcher_monochrome.png`);
}
mkdirSync(join(root, res, "mipmap-anydpi-v26"), { recursive: true });
writeFileSync(
  join(root, res, "mipmap-anydpi-v26/ic_launcher.xml"),
  `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by brand/build.mjs -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>
</adaptive-icon>
`,
);

// --- in-app logo (sign-in screen), 3x of 64dp
add(logo.tile(), 192, "apps/mobile/assets/brand/logo.png");

// Render
const browser = await chromium.launch();
const page = await browser.newPage();
for (const [svg, px, out] of jobs) {
  mkdirSync(dirname(out), { recursive: true });
  await page.setViewportSize({ width: px, height: px });
  await page.setContent(`<html><body style="margin:0">${svg.replace("<svg ", `<svg width="${px}" height="${px}" `)}</body></html>`);
  await page.screenshot({ path: out, omitBackground: true, clip: { x: 0, y: 0, width: px, height: px } });
}
await browser.close();

// Post-process: Apple rejects icons with an alpha channel; the web wants a multi-size favicon.ico.
const opaque = jobs.filter((j) => j[3]).map((j) => j[2]);
execFileSync("python3", ["-c", `
import sys
from PIL import Image
for p in sys.argv[2:]:
    im = Image.open(p).convert("RGBA"); bg = Image.new("RGB", im.size, (20, 82, 194)); bg.paste(im, mask=im.split()[3]); bg.save(p)
src = sys.argv[1]
Image.open(src + "/favicon-48.png").save("${join(root, "site/favicon.ico")}", sizes=[(16, 16), (32, 32), (48, 48)],
    append_images=[Image.open(src + "/favicon-16.png"), Image.open(src + "/favicon-32.png")])
`, join(root, "brand/out"), ...opaque]);
console.log(`rendered ${jobs.length} images (${opaque.length} made opaque) + favicon.ico`);
