// Embeds the skill (SKILL.md, references, base template) so `get_authoring_guide`
// can hand it to agents that don't have the skill installed.
import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const skill = join(here, "../../../skill");
const read = (p) => readFileSync(join(skill, p), "utf8");
const walk = (d) => readdirSync(d).flatMap((n) => (statSync(join(d, n)).isDirectory() ? walk(join(d, n)) : [join(d, n)]));
const template = Object.fromEntries(walk(join(skill, "templates/base")).map((p) => [relative(join(skill, "templates/base"), p), readFileSync(p, "utf8")]));
const out = {
  skill: read("SKILL.md").replace(/^---[\s\S]*?---\n/, ""),
  references: Object.fromEntries(readdirSync(join(skill, "reference")).map((n) => [n, read(`reference/${n}`)])),
  template,
};
mkdirSync(join(here, "../src/generated"), { recursive: true });
writeFileSync(join(here, "../src/generated/guide.ts"), `// GENERATED by scripts/gen-guide.mjs — do not edit.\nexport const GUIDE = ${JSON.stringify(out)} as const;\n`);
console.log("guide embedded:", Object.keys(template).join(", "));
